/* Phase 2 admin shell. Existing management actions and customer data stay intact. */
(() => {
'use strict';
const byId=id=>document.getElementById(id);
const panel=document.querySelector('#admin-section .panel-container');
if(!panel)return;
document.body.classList.add('admin-v2');
const nav=panel.querySelector('.tabs');
nav.classList.add('admin-nav');nav.setAttribute('aria-label','Panel principal');
const button=(id,label,tab)=>{const b=document.createElement('button');b.id=id;b.type='button';b.className='tab-btn';b.textContent=label;b.onclick=()=>switchTab(tab);return b;};
const home=document.createElement('section');home.id='tab-inicio';home.className='tab-content';
home.innerHTML='<div class="panel-page-heading"><div><p class="panel-eyebrow">Tu espacio de trabajo</p><h2>Resumen de la tienda</h2></div><button class="btn-primary" onclick="registroManual()">+ Registrar venta</button></div>';
home.append(panel.querySelector('.stats-container'),panel.querySelector('.attention-cards'));
const homeInfo=document.createElement('div');homeInfo.className='panel-note';
homeInfo.textContent='Revisa solicitudes, servicios que vencen y disponibilidad. Los mensajes se preparan aquí y los envías tú desde WhatsApp.';
home.append(homeInfo);
const settings=document.createElement('section');settings.id='tab-ajustes';settings.className='tab-content';
settings.innerHTML='<div class="panel-page-heading"><div><p class="panel-eyebrow">Control de tu tienda</p><h2>Ajustes y seguridad</h2></div></div><div class="settings-sections"><section><h3>Respaldo de gestión</h3><p>Descarga una copia cifrada y comprueba que puedas abrirla.</p><button class="btn-gestionar" onclick="abrirRespaldo()">Abrir respaldos</button></section><section><h3>Accesos administrativos</h3><p>Revisa los accesos registrados al panel.</p><button class="btn-gestionar" onclick="abrirSeguridad()">Ver accesos</button></section></div>';
const sections=document.createElement('div');sections.className='admin-workspace';
const header=panel.querySelector('.header-panel');
header.querySelector('h1').textContent='VegaStore';
header.querySelector('p').textContent='Administración';
header.querySelectorAll('[onclick="abrirRespaldo()"],[onclick="abrirSeguridad()"]').forEach(b=>b.remove());
const link=document.createElement('a');link.href='./';link.className='btn-gestionar';link.textContent='Ver tienda';header.lastElementChild.prepend(link);
const sidebar=document.createElement('aside');sidebar.className='admin-sidebar';
const layout=document.createElement('div');layout.className='admin-layout';
const subnav=document.createElement('div');subnav.className='panel-subnav';subnav.hidden=true;
subnav.append(byId('btn-tab-ventas'),byId('btn-tab-papelera'));
byId('btn-tab-ventas').textContent='Servicios contratados';byId('btn-tab-papelera').textContent='Archivados';
const profilesButton=button('btn-clientes-fichas','Fichas de clientes','fichas');subnav.prepend(profilesButton);
nav.prepend(button('btn-tab-inicio','Inicio','inicio'));
byId('btn-tab-fichas').textContent='Clientes';byId('btn-tab-solicitudes').textContent='Pedidos';
byId('btn-tab-seguimiento').textContent='Mensajes';byId('btn-tab-catalogo').textContent='Catálogo';
nav.append(button('btn-tab-ajustes','Ajustes','ajustes'));
for(const id of ['btn-tab-inicio','btn-tab-solicitudes','btn-tab-fichas','btn-tab-catalogo','btn-tab-seguimiento','btn-tab-ajustes'])nav.append(byId(id));
sidebar.append(nav);
sections.append(subnav,home,settings);
[...panel.children].filter(el=>el!==header&&el!==layout).forEach(el=>sections.append(el));
layout.append(sidebar,sections);panel.append(layout);
const originalSwitch=window.switchTab;
window.switchTab=function(tab){
 originalSwitch(tab);
 const customer=['fichas','ventas','papelera'].includes(tab);
 subnav.hidden=!customer;
 nav.querySelectorAll('.tab-btn').forEach(b=>b.classList.toggle('active',b.id==='btn-tab-'+(customer?'fichas':tab)));
 nav.querySelectorAll('.tab-btn').forEach(b=>{if(b.classList.contains('active'))b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});
 profilesButton.classList.toggle('active',tab==='fichas');
};
document.querySelectorAll('.tab-content,.tab-btn').forEach(e=>e.classList.remove('active'));
home.classList.add('active');byId('btn-tab-inicio').classList.add('active');
byId('btn-tab-inicio').setAttribute('aria-current','page');
})();