const { test } = require('node:test');
const assert = require('node:assert/strict');
const { readFileSync, readdirSync } = require('node:fs');
const { createHash } = require('node:crypto');
const { PGlite } = require('@electric-sql/pglite');

const owner = '00000000-0000-4000-8000-000000000001';
const outsider = '00000000-0000-4000-8000-000000000002';
const codeA = 'a'.repeat(48), codeB = 'b'.repeat(48);
const hash = x => createHash('sha256').update(x).digest('hex');

// Synthetic schema only: no production connection or customer data. PGlite runs
// PostgreSQL RLS/ACL checks; pgcrypto's SHA-256 is represented by PostgreSQL's built-in SHA-256.
const fixture = `
create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create schema storage; create schema extensions;
grant usage on schema public, auth, storage, extensions to anon, authenticated, service_role;
create table auth.users(id uuid primary key, deleted_at timestamptz, email_confirmed_at timestamptz);
insert into auth.users values ('${owner}',null,now());
create function auth.uid() returns uuid language sql stable as $$
 select (nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'sub')::uuid
$$;
`;

test('PostgreSQL enforces owner permissions, private links and restricted orders', async t => {
  const db = new PGlite();
  t.after(() => db.close());
  await db.exec(fixture);
  await db.exec(`
    create function extensions.digest(text,text) returns bytea language sql immutable as $$select sha256(convert_to($1,'UTF8'))$$;
    create function public.rls_auto_enable() returns event_trigger language plpgsql as $$begin return; end$$;
    create table public.usuarios_canva (
      id bigint generated always as identity primary key, correo text, metodo_pago text not null,
      num_operacion text, token text, estado text default 'Pendiente', fecha_inicio date, fecha_fin date,
      creado_en timestamptz default timezone('utc',now()), servicio text default 'Canva Pro Edu',
      meses int default 1, unidad text, telefono text, fecha_cancelacion timestamptz
    );
    create table public.servicios (
      id bigint generated always as identity primary key, nombre text not null, precio numeric not null,
      precio_promocional numeric, etiqueta text, caracteristicas text, activo boolean default true,
      planes jsonb default '[]', tipo_ingreso text default 'correo', categoria text, imagen_url text, geo_tipo text default 'todos',geo_paises text
    );
    create table public.admin_accesos(id bigint generated always as identity primary key, dispositivo text,navegador text,fecha timestamptz default now());
    create table public.promociones(id bigint generated by default as identity primary key,titulo text not null,descripcion text,precio_promo numeric,requisito_compra boolean default false,activo boolean default true,creado_en timestamptz default now());
    create table storage.buckets(id text primary key,public boolean,file_size_limit bigint,allowed_mime_types text[]);
    create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
    alter table storage.objects enable row level security;
    insert into storage.buckets values('imagenes_servicios',true,null,null);
    insert into storage.objects(bucket_id,name) values('imagenes_servicios','fixture.png');
    grant all on all tables in schema public,storage to anon,authenticated;
    grant all on all sequences in schema public to anon,authenticated;
    create policy "Old public access" on public.usuarios_canva for all to public using(true) with check(true);
    create policy "Permitir subida de imagenes 1f22wan_0" on storage.objects for insert to public with check(true);
    create policy "Permitir subida de imagenes 1f22wan_1" on storage.objects for select to public using(true);
    create policy "Permitir subida de imagenes 1f22wan_2" on storage.objects for update to public using(true);
    create policy "Permitir subida de imagenes 1f22wan_3" on storage.objects for delete to public using(true);
    insert into public.servicios(nombre,precio,planes) values ('Fixture service',10,'[{"cantidad":1,"unidad":"meses","precio":10}]');
    insert into public.servicios(nombre,precio,activo,planes) values ('Inactive fixture',10,false,'[{"cantidad":1,"unidad":"meses","precio":10}]');
    insert into public.promociones(titulo,activo) values('Visible',true),('Hidden',false);
  `);
  const migration = readdirSync('supabase/migrations').find(f => f.endsWith('_harden_vega_admin.sql'));
  await db.exec(readFileSync('supabase/migrations/' + migration, 'utf8'));
  await db.exec(`insert into public.usuarios_canva(correo,metodo_pago,servicio,consulta_hash,estado) values
    ('private-a@example.test','Manual','Fixture service','${hash(codeA)}','Activo'),
    ('private-b@example.test','Manual','Fixture service','${hash(codeB)}','Activo'),
    ('legacy@example.test','Manual','Fixture service',null,'Activo');`);
  const role = async (name, uid = null, code = null) => {
    await db.exec(`reset role; set role ${name};`);
    await db.query("select set_config('request.jwt.claims',$1,false),set_config('request.headers',$2,false)",
      [JSON.stringify(uid ? {sub:uid, role:name} : {}), JSON.stringify(code ? {'x-vega-access':code} : {})]);
  };
  const rows = async sql => (await db.query(sql)).rows;
  const denied = sql => assert.rejects(db.query(sql), e => e.code === '42501');
  const order = (patch={}) => {
    const data = {telefono:'+51900000000',correo:'fixture@example.test',servicio:'Fixture service',meses:1,unidad:'meses',metodo_pago:'WhatsApp',token:'TK-0123456789AB',consulta_hash:hash(codeA),...patch};
    const entries = Object.entries(data);
    return db.query(`insert into public.usuarios_canva(${entries.map(([k])=>k).join(',')}) values(${entries.map((_,i)=>'$'+(i+1)).join(',')})`,entries.map(([,v])=>v));
  };

  await t.test('anonymous visitors cannot list customers or read contact details', async () => {
    await role('anon');
    assert.equal((await rows('select id from public.usuarios_canva')).length,0);
    await denied('select * from public.usuarios_canva');
    await denied('select correo,telefono,token,consulta_hash from public.usuarios_canva');
    await denied('update public.usuarios_canva set estado=\'Activo\'');
    await denied('delete from public.usuarios_canva');
    await denied('select * from public.admin_accesos');
    await denied('select * from vega_private.admins');
    await denied("select setval('public.usuarios_canva_id_seq',1)");
    assert.equal((await rows('select id from public.servicios')).length,1);
    assert.equal((await rows('select id from public.promociones')).length,1);
  });
  await t.test('private codes scope reads; invalid codes and stored hashes cannot be used as codes', async () => {
    await role('anon',null,codeA);
    assert.deepEqual((await rows('select id from public.usuarios_canva')).map(r=>r.id),[1]);
    await denied('select correo from public.usuarios_canva');
    await role('anon',null,codeB);
    assert.deepEqual((await rows('select id from public.usuarios_canva')).map(r=>r.id),[2]);
    for(const invalid of [hash(codeA),'short',"' OR true --"]){
      await role('anon',null,invalid);
      assert.equal((await rows('select id from public.usuarios_canva')).length,0);
    }
  });
  await t.test('only valid pending purchases can be created, without contact-based data access', async () => {
    await role('anon',null,codeA);
    await order();
    assert.equal((await rows("select id from public.usuarios_canva where estado='Pendiente'")).length,1);
    for(const patch of [{estado:'Activo'}, {fecha_fin:'2099-01-01'}, {consulta_hash:hash(codeB)}, {meses:999}, {servicio:'Inactive fixture'}, {correo:'<img onerror=alert(1)>@example.test'}, {telefono:'invalid'}, {token:'bad'}, {correo:null}]) {
      await assert.rejects(order(patch), e=>e.code==='42501');
    }
    await order(); await order();
    await assert.rejects(order(), e=>e.code==='42501');
  });
  await t.test('registered non-admins cannot administer orders, catalogue, logs or allowlist', async () => {
    await role('authenticated',outsider,codeA);
    assert.equal((await rows('select public.is_vega_admin() as allowed'))[0].allowed,false);
    assert.equal((await rows('select * from public.usuarios_canva')).length,0);
    assert.equal((await rows("update public.usuarios_canva set estado='Activo' returning id")).length,0);
    assert.equal((await rows('delete from public.usuarios_canva returning id')).length,0);
    assert.equal((await rows("update public.servicios set nombre='forged' returning id")).length,0);
    assert.equal((await rows('delete from public.servicios returning id')).length,0);
    await assert.rejects(order(),e=>e.code==='42501');
    await denied("insert into public.servicios(nombre,precio) values('forged',0)");
    await denied("insert into public.admin_accesos(dispositivo) values('forged')");
    await denied(`insert into vega_private.admins values('${outsider}')`);
  });
  await t.test('anonymous visitors and other accounts cannot overwrite or delete product images', async () => {
    for(const identity of [['anon',null],['authenticated',outsider]]){
      await role(...identity);
      await denied("insert into storage.objects(bucket_id,name) values('imagenes_servicios','forged.png')");
      assert.equal((await rows("update storage.objects set name='forged' returning id")).length,0);
      assert.equal((await rows('delete from storage.objects returning id')).length,0);
    }
  });
  await t.test('verified owner retains management and can revoke old customer links', async () => {
    await role('authenticated',owner);
    assert.equal((await rows('select public.is_vega_admin() as allowed'))[0].allowed,true);
    assert.equal((await rows('select * from public.usuarios_canva')).length,6);
    assert.equal((await rows('select id from public.servicios')).length,2);
    await db.query("insert into public.admin_accesos(dispositivo,navegador) values('Fixture','Test')");
    await db.query(`update public.usuarios_canva set consulta_hash='${hash('c'.repeat(48))}' where id=1`);
    await db.query("update public.usuarios_canva set estado='Activo' where estado='Pendiente'");
    await db.query("update storage.objects set name='owner.png'");
    await role('anon',null,codeA);
    assert.equal((await rows('select id from public.usuarios_canva where id=1')).length,0);
    await role('anon',null,'c'.repeat(48));
    assert.equal((await rows('select id from public.usuarios_canva where id=1')).length,1);
  });

  await db.exec('reset role');
  // Test-only stand-in for pgcrypto randomness; real migrations use gen_random_bytes.
  await db.exec(`create function extensions.gen_random_bytes(integer) returns bytea language sql volatile as $$
      select substring(decode(replace(gen_random_uuid()::text || gen_random_uuid()::text,'-',''),'hex') from 1 for $1)
  $$;`);
  const beforeProfiles=await rows('select id,consulta_hash,correo,estado,fecha_fin from public.usuarios_canva order by id');
  const profileMigration=readdirSync('supabase/migrations').find(f=>f.endsWith('_client_profiles_and_messages.sql'));
  await db.exec(readFileSync('supabase/migrations/'+profileMigration,'utf8'));
  assert.deepEqual(await rows('select id,consulta_hash,correo,estado,fecha_fin from public.usuarios_canva order by id'),beforeProfiles);
  let stable, manualId;
  await t.test('profiles preserve existing private links and offer reusable links to all associated services',async()=>{
    await role('authenticated',owner);
    const first=(await rows('select * from public.vega_ficha_pedido(1)'))[0];
    const second=(await rows('select * from public.vega_ficha_pedido(1)'))[0];
    assert.equal(first.codigo_privado,second.codigo_privado);
    assert.match(first.codigo_privado,/^[a-f0-9]{48}$/);
    stable=first;
    manualId=(await db.query("select public.vega_registro_manual($1,null,null,null,null,'Second service',3,'meses') as id",[first.id])).rows[0].id;
    await role('anon',null,'c'.repeat(48));assert.equal((await rows('select id from public.usuarios_canva where id=1')).length,1);
    await role('anon',null,first.codigo_privado);
    assert.equal((await rows('select id from public.usuarios_canva')).length,2);
    await denied('select codigo_privado from public.vega_clientes');
    await denied('select cliente_id,cliente_consulta_hash from public.usuarios_canva');
  });
  await t.test('manual registration accepts username only and contact edits keep identity and links',async()=>{
    await role('authenticated',owner);
    const id=(await rows("select public.vega_registro_manual(null,'María',null,'maria_test',null,'Manual fixture',1,'meses') as id"))[0].id;
    const ficha=(await rows(`select * from public.vega_ficha_pedido(${id})`))[0];
    assert.equal(ficha.telefono,null);assert.equal(ficha.whatsapp_usuario,'maria_test');
    await db.query("update public.vega_clientes set nombre='Nuevo nombre',telefono='+51911111111',whatsapp_usuario='nuevo_usuario' where id=$1",[ficha.id]);
    const updated=(await rows(`select * from public.vega_ficha_pedido(${id})`))[0];
    assert.equal(updated.id,ficha.id);assert.equal(updated.codigo_privado,ficha.codigo_privado);
    const order=(await rows(`select * from public.usuarios_canva where id=${id}`))[0];
    assert.equal(order.telefono,updated.telefono);assert.equal(order.whatsapp_usuario,updated.whatsapp_usuario);
  });
  await t.test('guest username orders cannot attach to existing profiles by claiming their contact',async()=>{
    await role('anon',null,codeA);
    await order({telefono:null,whatsapp_usuario:'nuevo_usuario'});
    await assert.rejects(order({telefono:null,whatsapp_usuario:null}),e=>e.code==='42501');
    await assert.rejects(order({cliente_id:stable.id}),e=>e.code==='42501');
    await denied('select * from public.vega_ficha_pedido(1)');
    await role('authenticated',owner);
    const guest=(await rows("select * from public.usuarios_canva where estado='Pendiente' and whatsapp_usuario='nuevo_usuario'"))[0];
    assert.equal(guest.cliente_id,null);
    const resolved=(await rows(`select * from public.vega_ficha_pedido(${guest.id})`))[0];
    const victim=(await rows("select * from public.vega_clientes where nombre='Nuevo nombre'"))[0];
    assert.notEqual(resolved.id,victim.id);
  });
  await t.test('non-admin accounts cannot read link secrets or invoke profile mutations',async()=>{
    await role('authenticated',outsider);
    assert.equal((await rows('select * from public.vega_clientes')).length,0);
    assert.equal((await rows("update public.vega_clientes set nombre='forged' returning id")).length,0);
    await denied('select * from public.vega_ficha_pedido(1)');
    await denied("select public.vega_registro_manual(null,'forged',null,null,null,'forged',1,'meses')");
    await denied("insert into public.vega_clientes(nombre) values('forged')");
  });
  await t.test('explicit revocation removes both the stable link and all legacy links',async()=>{
    await role('authenticated',owner);
    await db.query("update public.vega_clientes set codigo_privado=$1 where id=$2",['e'.repeat(48),stable.id]);
    for(const old of [stable.codigo_privado,'c'.repeat(48)]){
      await role('anon',null,old);assert.equal((await rows('select id from public.usuarios_canva where id=1')).length,0);
    }
    await role('anon',null,'e'.repeat(48));assert.equal((await rows('select id from public.usuarios_canva')).length,2);
    await role('authenticated',owner);
    const target=(await rows("select * from public.vega_clientes where whatsapp_usuario='nuevo_usuario' and nombre='Nuevo nombre'"))[0];
    await db.query('update public.usuarios_canva set cliente_id=$1 where id=$2',[target.id,manualId]);
    await role('anon',null,'e'.repeat(48));assert.equal((await rows('select id from public.usuarios_canva')).length,1);
    await role('anon',null,target.codigo_privado);assert.equal((await rows(`select id from public.usuarios_canva where id=${manualId}`)).length,1);
  });
  await db.exec('reset role');
  const beforeStock=await rows('select id,consulta_hash,cliente_consulta_hash,correo,estado,fecha_fin from public.usuarios_canva order by id');
  const stockMigration=readdirSync('supabase/migrations').find(f=>f.endsWith('_stock_and_scheduled_offers.sql'));
  await db.exec(readFileSync('supabase/migrations/'+stockMigration,'utf8'));
  assert.deepEqual(await rows('select id,consulta_hash,cliente_consulta_hash,correo,estado,fecha_fin from public.usuarios_canva order by id'),beforeStock);
  let stockId, firstOrder, secondOrder;
  await t.test('inventory defaults preserve existing sales and catalogue prices',async()=>{
    await role('authenticated',owner);
    assert.equal((await rows('select count(*)::int n from public.servicios where stock is not null or agotado'))[0].n,0);
    assert.equal((await rows("select count(*)::int n from public.usuarios_canva where estado='Activo' and not stock_descontado"))[0].n,0);
    stockId=(await rows(`insert into public.servicios(nombre,precio,planes,stock,tipo_ingreso)
      values ('Limited fixture',20,'[{"cantidad":1,"unidad":"meses","precio":20,"promo":10}]',1,'numero') returning id`))[0].id;
  });
  await t.test('pending requests do not consume stock; database validates scheduled prices',async()=>{
    await role('authenticated',owner);
    await db.query("update public.servicios set promocion_inicio=now()-interval '1 hour',promocion_fin=now()+interval '1 hour' where id=$1",[stockId]);
    await role('anon',null,'d'.repeat(48));
    const purchase={servicio_id:stockId,servicio:'Limited fixture',correo:null,consulta_hash:hash('d'.repeat(48)),precio_acordado:10};
    await assert.rejects(order({...purchase,precio_acordado:1}),/precio cambió/);
    await order(purchase); await order(purchase);
    const pending=await rows("select id,precio_acordado from public.usuarios_canva where estado='Pendiente' order by id");
    assert.equal(pending.length,2);assert.equal(Number(pending[0].precio_acordado),10);
    firstOrder=pending[0].id;secondOrder=pending[1].id;
    assert.equal((await rows(`select stock from public.servicios where id=${stockId}`))[0].stock,1);
    await role('authenticated',owner);
    await db.query("update public.servicios set promocion_inicio=now()-interval '2 hours',promocion_fin=now()-interval '1 hour' where id=$1",[stockId]);
    await role('anon',null,'d'.repeat(48));
    await assert.rejects(order(purchase),/precio cambió/);
    await order({...purchase,precio_acordado:20});
    await role('authenticated',owner);
    await db.query("update public.servicios set promocion_inicio=now()+interval '1 hour',promocion_fin=now()+interval '2 hours' where id=$1",[stockId]);
    await role('anon',null,'f'.repeat(48));
    await assert.rejects(order({...purchase,consulta_hash:hash('f'.repeat(48))}),/precio cambió/);
  });
  await t.test('only one approval can consume the last unit and retries never decrement twice',async()=>{
    await role('authenticated',owner);
    await db.query(`update public.usuarios_canva set estado='Activo' where id=${firstOrder}`);
    assert.equal((await rows(`select stock from public.servicios where id=${stockId}`))[0].stock,0);
    await assert.rejects(db.query(`update public.usuarios_canva set estado='Activo' where id=${secondOrder}`),/agotado/);
    assert.equal((await rows(`select estado from public.usuarios_canva where id=${secondOrder}`))[0].estado,'Pendiente');
    for(const estado of ['Activo','Cancelado','Activo'])await db.query(`update public.usuarios_canva set estado=$1,stock_descontado=false where id=${firstOrder}`,[estado]);
    assert.equal((await rows(`select stock from public.servicios where id=${stockId}`))[0].stock,0);
    assert.equal(Number((await rows(`select precio_acordado from public.usuarios_canva where id=${firstOrder}`))[0].precio_acordado),10);
    assert.equal((await rows(`update public.servicios set stock=10 where id=${stockId} and stock_version=0 returning id`)).length,0);
    await assert.rejects(db.query(`update public.servicios set stock=-1 where id=${stockId}`),e=>e.code==='23514');
  });
  await t.test('manual sales consume inventory atomically and out-of-stock failures leave no profile',async()=>{
    await role('authenticated',owner);
    const count=(await rows('select count(*)::int n from public.vega_clientes'))[0].n;
    const register=()=>db.query("select public.vega_registro_manual(null,'Stock buyer',null,'stock_buyer',null,'Limited fixture',1,'meses',$1) as id",[stockId]);
    await assert.rejects(register(),/agotado/);
    assert.equal((await rows('select count(*)::int n from public.vega_clientes'))[0].n,count);
    await db.query(`update public.servicios set stock=2 where id=${stockId}`);
    await register();assert.equal((await rows(`select stock from public.servicios where id=${stockId}`))[0].stock,1);
    await db.query(`update public.servicios set agotado=true where id=${stockId}`);
    await assert.rejects(register(),/agotado/);
    await db.query(`update public.servicios set agotado=false where id=${stockId}`);
  });
  await t.test('duplicate names require the exact product and guests cannot manipulate stock or activation',async()=>{
    await role('authenticated',owner);
    const duplicate=(await rows(`insert into public.servicios(nombre,precio,planes,stock,tipo_ingreso)
      values ('Limited fixture',7,'[{"cantidad":1,"unidad":"meses","precio":7}]',0,'numero') returning id`))[0].id;
    await role('anon',null,'9'.repeat(48));
    const purchase={servicio:'Limited fixture',correo:null,consulta_hash:hash('9'.repeat(48))};
    await assert.rejects(order(purchase),/varios productos/);
    await assert.rejects(order({...purchase,servicio_id:duplicate}),/agotado/);
    await order({...purchase,servicio_id:stockId,precio_acordado:20});
    await assert.rejects(order({...purchase,servicio_id:stockId,stock_descontado:true}),e=>e.code==='42501');
    await denied(`update public.servicios set stock=100 where id=${stockId}`);
    await denied(`update public.usuarios_canva set estado='Activo' where id=${secondOrder}`);
    await role('authenticated',outsider);
    assert.equal((await rows(`update public.servicios set stock=100 where id=${stockId} returning id`)).length,0);
    await denied(`select public.vega_registro_manual(null,'Fake',null,null,null,'Limited fixture',1,'meses',${stockId})`);
  });

  await db.exec('reset role');
  const beforeManagement=await rows('select id,fecha_fin,fecha_inicio,consulta_hash,cliente_consulta_hash,meses,unidad from public.usuarios_canva order by id');
  await db.exec(readFileSync('supabase/migrations/20260913204706_service_management_and_history.sql','utf8'));
  assert.deepEqual(await rows('select id,fecha_fin,fecha_inicio,consulta_hash,cliente_consulta_hash,meses,unidad from public.usuarios_canva order by id'),beforeManagement);
  let managed, operation='11111111-1111-4111-8111-111111111111';
  await t.test('manual sale retries preserve one order and one inventory debit',async()=>{
    await role('authenticated',owner);
    const params=[null,'Fixture member',null,'fixture_member',null,'External fixture',1,'meses',null,operation];
    const q='select public.vega_registro_seguro($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) id';
    managed=(await db.query(q,params)).rows[0].id;
    assert.equal((await db.query(q,params)).rows[0].id,managed);
    params[6]=2;await assert.rejects(db.query(q,params),/otros datos/);
    assert.equal((await rows(`select count(*)::int n from public.vega_movimientos where operacion='${operation}'`))[0].n,1);
  });
  await t.test('month-end extension is atomic, audited, idempotent and rejects stale or invalid changes',async()=>{
    await role('authenticated',owner);
    await db.query("update public.usuarios_canva set fecha_inicio='2028-01-31',vigencia_inicio='2028-01-31',fecha_fin='2028-01-31' where id=$1",[managed]);
    const p=(await rows(`select * from public.usuarios_canva where id=${managed}`))[0];
    const args=[managed,1,'meses','sumar','regalo',p.version,'22222222-2222-4222-8222-222222222222'];
    const q='select public.vega_actualizar_vigencia($1,$2,$3,$4,$5,$6,$7)::text ending';
    const res=(await db.query(q,args)).rows[0];assert.equal(res.ending,'2028-02-29');
    assert.equal((await db.query(q,args)).rows[0].ending,res.ending);
    args[6]='33333333-3333-4333-8333-333333333333';await assert.rejects(db.query(q,args),/cambió/);
    args[1]=-1;await assert.rejects(db.query(q,args),/duración/);
    args[1]=101;args[2]='años';await assert.rejects(db.query(q,args),/duración/);
    const changed=(await rows(`select * from public.usuarios_canva where id=${managed}`))[0];assert.equal(changed.meses,1);assert.match(changed.ultima_ampliacion,/1 mes/);
    assert.equal((await rows(`select count(*)::int n from public.vega_movimientos where pedido_id=${managed} and tipo='regalo'`))[0].n,1);
    await denied(`delete from public.usuarios_canva where id=${managed}`);
    await denied(`delete from public.vega_movimientos where pedido_id=${managed}`);
    await denied(`update public.vega_movimientos set tipo='fake' where pedido_id=${managed}`);
    await assert.rejects(db.query(`insert into public.vega_movimientos(pedido_id,tipo,actor) values(${managed},'fake','${owner}')`),e=>e.code==='42501');
  });
  await t.test('expired renewal starts today; archive and restore preserve expiry and original status',async()=>{
    await role('authenticated',owner);
    await db.query("update public.usuarios_canva set fecha_inicio='2020-01-01',vigencia_inicio='2020-01-01',fecha_fin='2020-02-01' where id=$1",[managed]);
    let p=(await rows(`select * from public.usuarios_canva where id=${managed}`))[0];
    await db.query("select public.vega_actualizar_vigencia($1,1,'meses','sumar','renovacion',$2,$3)",[managed,p.version,'44444444-4444-4444-8444-444444444444']);
    const correct=(await rows(`select vigencia_inicio=(now() at time zone 'America/Lima')::date start_ok,fecha_fin=((now() at time zone 'America/Lima')::date+interval '1 month')::date end_ok from public.usuarios_canva where id=${managed}`))[0];assert.equal(correct.start_ok,true);assert.equal(correct.end_ok,true);
    p=(await rows(`select * from public.usuarios_canva where id=${managed}`))[0];
    await db.query('select public.vega_archivar_servicio($1,$2,false)',[managed,p.version]);
    const archived=(await rows(`select * from public.usuarios_canva where id=${managed}`))[0];assert.equal(archived.estado,'Cancelado');
    await db.query('select public.vega_archivar_servicio($1,$2,true)',[managed,archived.version]);
    const restored=(await rows(`select * from public.usuarios_canva where id=${managed}`))[0];assert.equal(restored.estado,'Activo');assert.deepEqual(restored.fecha_fin,p.fecha_fin);
    let pending=(await rows("select * from public.usuarios_canva where estado='Pendiente' limit 1"))[0];
    await db.query('select public.vega_archivar_servicio($1,$2,false)',[pending.id,pending.version]);
    pending=(await rows(`select * from public.usuarios_canva where id=${pending.id}`))[0];
    await db.query('select public.vega_archivar_servicio($1,$2,true)',[pending.id,pending.version]);
    assert.equal((await rows(`select estado from public.usuarios_canva where id=${pending.id}`))[0].estado,'Pendiente');
  });
  await t.test('history is private, follows link revocation, and never exposes internal audit fields',async()=>{
    await role('authenticated',owner);
    const c=(await rows(`select c.* from public.vega_clientes c join public.usuarios_canva u on c.id=u.cliente_id where u.id=${managed}`))[0];
    await role('anon',null,c.codigo_privado);
    assert.ok((await rows(`select id,tipo from public.vega_movimientos where pedido_id=${managed}`)).length>0);
    assert.equal((await rows(`select id from public.vega_movimientos where pedido_id<>${managed}`)).length,0);
    await denied('select actor,detalle,solicitud_hash from public.vega_movimientos');
    await denied('select * from public.vega_auditoria');
    await denied(`select public.vega_archivar_servicio(${managed},0,false)`);
    await role('authenticated',outsider);
    assert.equal((await rows('select * from public.vega_movimientos')).length,0);
    await denied(`select public.vega_actualizar_vigencia(${managed},1,'meses','sumar','regalo',0,gen_random_uuid())`);
    await role('authenticated',owner);
    await db.query('update public.vega_clientes set codigo_privado=$1 where id=$2',['1'.repeat(48),c.id]);
    await role('anon',null,c.codigo_privado);assert.equal((await rows('select id from public.vega_movimientos')).length,0);
  });

  await db.exec('reset role');
  const backupMigration=readdirSync('supabase/migrations').find(f=>f.endsWith('_encrypted_management_backup.sql'));
  await db.exec(readFileSync('supabase/migrations/'+backupMigration,'utf8'));
  await t.test('management export denies guests, private links and unrelated accounts',async()=>{
    await role('anon');await denied('select public.vega_exportar_datos()');
    await role('anon',null,codeA);await denied('select public.vega_exportar_datos()');
    await role('authenticated',outsider);await denied('select public.vega_exportar_datos()');
    await db.exec('reset role');
    assert.equal((await rows("select prosecdef from pg_proc where oid='public.vega_exportar_datos()'::regprocedure"))[0].prosecdef,false);
  });
  await t.test('encrypted snapshot restores all management rows, stock and private links into isolated tables',async()=>{
    const backup=require('../respaldo.js');
    await role('authenticated',owner);
    // More than PostgREST's normal page size: the RPC must never silently truncate.
    await db.exec("insert into public.vega_clientes(nombre) select 'Bulk fixture '||n from generate_series(1,1005) n");
    const raw=(await rows('select public.vega_exportar_datos() value'))[0].value;
    const encrypted=await backup.encrypt(raw,'Synthetic backup password only');
    const recovered=await backup.decrypt(encrypted,'Synthetic backup password only');
    assert.equal(recovered.text,raw);
    const data=JSON.parse(recovered.text).tables;
    assert.ok(data.vega_clientes.length>1000);
    await db.exec('reset role; create schema restore_check');
    for(const name of Object.keys(data))await db.exec(`create table restore_check.${name} (like public.${name} including all)`);
    await db.exec(`
      alter table restore_check.usuarios_canva add foreign key(cliente_id) references restore_check.vega_clientes(id);
      alter table restore_check.usuarios_canva add foreign key(servicio_id) references restore_check.servicios(id);
      alter table restore_check.vega_movimientos add foreign key(pedido_id) references restore_check.usuarios_canva(id);
      alter table restore_check.vega_avisos_manuales add foreign key(pedido_id) references restore_check.usuarios_canva(id);
    `);
    for(const name of ['servicios','vega_clientes','usuarios_canva','promociones','vega_movimientos','vega_avisos_manuales','vega_auditoria','admin_accesos']){
      const columns=(await db.query("select column_name from information_schema.columns where table_schema='restore_check' and table_name=$1 and is_generated='NEVER' order by ordinal_position",[name])).rows.map(r=>'"'+r.column_name+'"').join(',');
      await db.query(`insert into restore_check.${name} (${columns}) overriding system value select ${columns} from jsonb_populate_recordset(null::restore_check.${name},$1::jsonb)`,[JSON.stringify(data[name])]);
      const matches=(await rows(`select not exists ((select to_jsonb(t) from public.${name} t except all select to_jsonb(t) from restore_check.${name} t) union all (select to_jsonb(t) from restore_check.${name} t except all select to_jsonb(t) from public.${name} t)) matches`))[0].matches;
      assert.equal(matches,true,name+' restored exactly');
    }
    // Restoring data does not call the live sale/stock/gift triggers.
    assert.deepEqual(await rows('select id,stock,stock_version from restore_check.servicios order by id'),await rows('select id,stock,stock_version from public.servicios order by id'));
    await db.exec('drop schema restore_check cascade');
  });

});
