const { test } = require('node:test');
const assert = require('node:assert/strict');
const { readFileSync, readdirSync } = require('node:fs');
const { createHash } = require('node:crypto');
const { PGlite } = require('@electric-sql/pglite');

const owner = '00000000-0000-4000-8000-000000000001';
const outsider = '00000000-0000-4000-8000-000000000002';
const codeA = 'a'.repeat(48), codeB = 'b'.repeat(48);
const hash = x => createHash('sha256').update(x).digest('hex');

// Synthetic schema only: no production connection or customer data. PGlite runs
// PostgreSQL RLS/ACL checks; pgcrypto's SHA-256 is represented by PostgreSQL's built-in SHA-256.
const fixture = `
create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create schema storage; create schema extensions;
grant usage on schema public, auth, storage, extensions to anon, authenticated, service_role;
create table auth.users(id uuid primary key, deleted_at timestamptz, email_confirmed_at timestamptz);
insert into auth.users values ('${owner}',null,now());
create function auth.uid() returns uuid language sql stable as $$
 select (nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'sub')::uuid
$$;
`;

test('PostgreSQL enforces owner permissions, private links and restricted orders', async t => {
  const db = new PGlite();
  t.after(() => db.close());
  await db.exec(fixture);
  await db.exec(`
    create function extensions.digest(text,text) returns bytea language sql immutable as $$select sha256(convert_to($1,'UTF8'))$$;
    create function public.rls_auto_enable() returns event_trigger language plpgsql as $$begin return; end$$;
    create table public.usuarios_canva (
      id bigint generated always as identity primary key, correo text, metodo_pago text not null,
      num_operacion text, token text, estado text default 'Pendiente', fecha_inicio date, fecha_fin date,
      creado_en timestamptz default timezone('utc',now()), servicio text default 'Canva Pro Edu',
      meses int default 1, unidad text, telefono text, fecha_cancelacion timestamptz
    );
    create table public.servicios (
      id bigint generated always as identity primary key, nombre text not null, precio numeric not null,
      precio_promocional numeric, etiqueta text, caracteristicas text, activo boolean default true,
      planes jsonb default '[]', tipo_ingreso text default 'correo', categoria text, imagen_url text, geo_tipo text default 'todos',geo_paises text
    );
    create table public.admin_accesos(id bigint generated always as identity primary key, dispositivo text,navegador text,fecha timestamptz default now());
    create table public.promociones(id bigint generated by default as identity primary key,titulo text not null,descripcion text,precio_promo numeric,requisito_compra boolean default false,activo boolean default true,creado_en timestamptz default now());
    create table storage.buckets(id text primary key,public boolean,file_size_limit bigint,allowed_mime_types text[]);
    create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text);
    alter table storage.objects enable row level security;
    insert into storage.buckets values('imagenes_servicios',true,null,null);
    insert into storage.objects(bucket_id,name) values('imagenes_servicios','fixture.png');
    grant all on all tables in schema public,storage to anon,authenticated;
    grant all on all sequences in schema public to anon,authenticated;
    create policy "Old public access" on public.usuarios_canva for all to public using(true) with check(true);
    create policy "Permitir subida de imagenes 1f22wan_0" on storage.objects for insert to public with check(true);
    create policy "Permitir subida de imagenes 1f22wan_1" on storage.objects for select to public using(true);
    create policy "Permitir subida de imagenes 1f22wan_2" on storage.objects for update to public using(true);
    create policy "Permitir subida de imagenes 1f22wan_3" on storage.objects for delete to public using(true);
    insert into public.servicios(nombre,precio,planes) values ('Fixture service',10,'[{"cantidad":1,"unidad":"meses","precio":10}]');
    insert into public.servicios(nombre,precio,activo,planes) values ('Inactive fixture',10,false,'[{"cantidad":1,"unidad":"meses","precio":10}]');
    insert into public.promociones(titulo,activo) values('Visible',true),('Hidden',false);
  `);
  const migration = readdirSync('supabase/migrations').find(f => f.endsWith('_harden_vega_admin.sql'));
  await db.exec(readFileSync('supabase/migrations/' + migration, 'utf8'));
  await db.exec(`insert into public.usuarios_canva(correo,metodo_pago,servicio,consulta_hash,estado) values
    ('private-a@example.test','Manual','Fixture service','${hash(codeA)}','Activo'),
    ('private-b@example.test','Manual','Fixture service','${hash(codeB)}','Activo'),
    ('legacy@example.test','Manual','Fixture service',null,'Activo');`);
  const role = async (name, uid = null, code = null) => {
    await db.exec(`reset role; set role ${name};`);
    await db.query("select set_config('request.jwt.claims',$1,false),set_config('request.headers',$2,false)",
      [JSON.stringify(uid ? {sub:uid, role:name} : {}), JSON.stringify(code ? {'x-vega-access':code} : {})]);
  };
  const rows = async sql => (await db.query(sql)).rows;
  const denied = sql => assert.rejects(db.query(sql), e => e.code === '42501');
  const order = (patch={}) => {
    const data = {telefono:'+51900000000',correo:'fixture@example.test',servicio:'Fixture service',meses:1,unidad:'meses',metodo_pago:'WhatsApp',token:'TK-0123456789AB',consulta_hash:hash(codeA),...patch};
    const entries = Object.entries(data);
    return db.query(`insert into public.usuarios_canva(${entries.map(([k])=>k).join(',')}) values(${entries.map((_,i)=>'$'+(i+1)).join(',')})`,entries.map(([,v])=>v));
  };

  await t.test('anonymous visitors cannot list customers or read contact details', async () => {
    await role('anon');
    assert.equal((await rows('select id from public.usuarios_canva')).length,0);
    await denied('select * from public.usuarios_canva');
    await denied('select correo,telefono,token,consulta_hash from public.usuarios_canva');
    await denied('update public.usuarios_canva set estado=\'Activo\'');
    await denied('delete from public.usuarios_canva');
    await denied('select * from public.admin_accesos');
    await denied('select * from vega_private.admins');
    await denied("select setval('public.usuarios_canva_id_seq',1)");
    assert.equal((await rows('select id from public.servicios')).length,1);
    assert.equal((await rows('select id from public.promociones')).length,1);
  });
  await t.test('private codes scope reads; invalid codes and stored hashes cannot be used as codes', async () => {
    await role('anon',null,codeA);
    assert.deepEqual((await rows('select id from public.usuarios_canva')).map(r=>r.id),[1]);
    await denied('select correo from public.usuarios_canva');
    await role('anon',null,codeB);
    assert.deepEqual((await rows('select id from public.usuarios_canva')).map(r=>r.id),[2]);
    for(const invalid of [hash(codeA),'short',"' OR true --"]){
      await role('anon',null,invalid);
      assert.equal((await rows('select id from public.usuarios_canva')).length,0);
    }
  });
  await t.test('only valid pending purchases can be created, without contact-based data access', async () => {
    await role('anon',null,codeA);
    await order();
    assert.equal((await rows("select id from public.usuarios_canva where estado='Pendiente'")).length,1);
    for(const patch of [{estado:'Activo'}, {fecha_fin:'2099-01-01'}, {consulta_hash:hash(codeB)}, {meses:999}, {servicio:'Inactive fixture'}, {correo:'<img onerror=alert(1)>@example.test'}, {telefono:'invalid'}, {token:'bad'}, {correo:null}]) {
      await assert.rejects(order(patch), e=>e.code==='42501');
    }
    await order(); await order();
    await assert.rejects(order(), e=>e.code==='42501');
  });
  await t.test('registered non-admins cannot administer orders, catalogue, logs or allowlist', async () => {
    await role('authenticated',outsider,codeA);
    assert.equal((await rows('select public.is_vega_admin() as allowed'))[0].allowed,false);
    assert.equal((await rows('select * from public.usuarios_canva')).length,0);
    assert.equal((await rows("update public.usuarios_canva set estado='Activo' returning id")).length,0);
    assert.equal((await rows('delete from public.usuarios_canva returning id')).length,0);
    assert.equal((await rows("update public.servicios set nombre='forged' returning id")).length,0);
    assert.equal((await rows('delete from public.servicios returning id')).length,0);
    await assert.rejects(order(),e=>e.code==='42501');
    await denied("insert into public.servicios(nombre,precio) values('forged',0)");
    await denied("insert into public.admin_accesos(dispositivo) values('forged')");
    await denied(`insert into vega_private.admins values('${outsider}')`);
  });
  await t.test('anonymous visitors and other accounts cannot overwrite or delete product images', async () => {
    for(const identity of [['anon',null],['authenticated',outsider]]){
      await role(...identity);
      await denied("insert into storage.objects(bucket_id,name) values('imagenes_servicios','forged.png')");
      assert.equal((await rows("update storage.objects set name='forged' returning id")).length,0);
      assert.equal((await rows('delete from storage.objects returning id')).length,0);
    }
  });
  await t.test('verified owner retains management and can revoke old customer links', async () => {
    await role('authenticated',owner);
    assert.equal((await rows('select public.is_vega_admin() as allowed'))[0].allowed,true);
    assert.equal((await rows('select * from public.usuarios_canva')).length,6);
    assert.equal((await rows('select id from public.servicios')).length,2);
    await db.query("insert into public.admin_accesos(dispositivo,navegador) values('Fixture','Test')");
    await db.query(`update public.usuarios_canva set consulta_hash='${hash('c'.repeat(48))}' where id=1`);
    await db.query("update public.usuarios_canva set estado='Activo' where estado='Pendiente'");
    await db.query("update storage.objects set name='owner.png'");
    await role('anon',null,codeA);
    assert.equal((await rows('select id from public.usuarios_canva where id=1')).length,0);
    await role('anon',null,'c'.repeat(48));
    assert.equal((await rows('select id from public.usuarios_canva where id=1')).length,1);
  });
});
